version: "2" # Versão do docker-compose
services:
  db: # Informa o nome do serviço a ser criado
    build: # Informa que serão informados dados da construção
      context: .././src/bd # Informa o contexto a ser criado
      dockerfile: Dockerfile # Informa onde está o arquivo Dockerfile da imagem
    container_name: container-postgres # Nome da instância da imagem a ser criada
    restart: always
    volumes: # Informa os volumes do Container
      - .././src/bd/data:/var/lib/postgresql/data
    environment: # Informa as variáveis de ambiente
      POSTGRES_DIALECT: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: orderapp
    ports: # Informa o mapeamento de portas
      - 5432:5432
  app: 
    build:
      context: .././
      dockerfile: Dockerfile
    command: yarn dev
    container_name: container-nodejs
    volumes:
      - .././:/app/order-app
    environment:
      PORT: 8080
      NODE_ENV: dev
    ports:
      - 8080:8080
    depends_on:
      - db
