# Pulls Postgres:12-Alpine image from DockerHub.
FROM postgres:12-alpine

# Set the DB variables
ENV POSTGRES_PASSWORD=docker
ENV POSTGRES_PORT=5432
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=docker
ENV POSTGRES_DB=orderapp